site_name: XAROPi

theme:
  name: material
  language: pt
  logo: assets/images/logo-xaropi.svg 
  palette:
    scheme: slate 
    primary: black 
    accent: deep orange 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.follow

plugins:
  - search:
      enabled: false

nav:
  - HOME: index.md
  - ENTREGA 1: 
      - Introdução: entrega1/introducao.md
      - Requisitos: entrega1/requisitos.md 
  - ENTREGA 2: 
      - Introdução: entrega2/introducao.md
  - ENTREGA 3: 
      - Introdução: entrega3/introducao.md


extra_css:
  - assets/css/extra.css
  