site_name: XAROPi
site_url: https://fcte-pi1.github.io/2026.1_PI1_Grupo01_Bruno/
theme:
  name: material
  language: pt
  logo: assets/images/logo-xaropi.svg 
  palette:
    scheme: slate 
    primary: black 
    accent: deep orange 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.follow

plugins:
  - search:
      enabled: false

nav:
  - HOME: index.md
  - ENTREGA 1: 
      - Requisitos: entrega1/requisitos.md 
      - Descrição de Software: entrega1/descricao_software.md 
  - ENTREGA 2: 
      - Em breve: entrega2/introducao.md
  - ENTREGA 3: 
      - Em breve: entrega3/introducao.md


extra_css:
  - assets/css/extra.css
  